# -*- coding: utf-8 -*-
"""MDCredit Card Fraud Detection .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kK_ixculKZtZoActyjTgTAcdVfaUAfh4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

df=pd.read_csv("/content/creditcard.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

df=df.dropna()

df.duplicated().sum()

df=df.drop_duplicates()

# for i in df.columns:
#   print(df[i].value_counts())
#   print("="*50)

df.describe()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

x=df.drop(columns="Class")
y=df["Class"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2,stratify=y)

scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

model=Sequential()
model.add(Dense(64,activation="relu",input_dim=30))
model.add(Dropout(0.3))
model.add(Dense(32,activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(16,activation="relu"))
model.add(Dropout(0.3))
# model.add(Dense(60,activation="relu"))
# model.add(Dropout(0.3))
# model.add(Dense(50,activation="relu"))
# model.add(Dropout(0.3))
model.add(Dense(1,activation="sigmoid"))

callback=EarlyStopping(
    monitor="val_loss",
    patience=5,
   restore_best_weights=True
)

model.compile(loss="binary_crossentropy",optimizer=Adam(learning_rate=0.001),metrics=["accuracy"])

model.fit(x_train_scaled,y_train,batch_size=100,validation_split=0.2,epochs=50,callbacks=callback)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

pred=model.predict(x_test_scaled)
y_pred = (pred > 0.5).astype(int).flatten()

classification_report(y_pred,y_test)

confusion_matrix(y_pred,y_test)

